/**
 * @file parser.hpp
 * @brief Declaration of the FParser class.
 */

// Ensure this file is included only once
#pragma once

// Include the interface for language statements
#include "statement/interface/statement.hpp"

// Include the interface for expressions
#include "expression/interface/expression.hpp"

// Include the expression parser header file
#include "expression_parser.hpp"

// Include the statement parser header file
#include "statement_parser.hpp"

// Forward declaration of FLexer class
class FLexer;

/**
 * @brief Represents a parser for the custom language.
 *
 * This class is responsible for parsing tokens generated by the tokenizer
 * into an abstract syntax tree (AST) representation of the program.
 */
class FParser final
{
    // Reference to the lexer used by the parser
    FLexer& m_lexer;

    // Expression parser object
    FExpressionParser m_expressionParser;

    // Statement parser object
    FStatementParser m_statementParser;

public:

    /**
     * @brief Constructs a parser with the given lexer.
     * @param lexer The lexer to be used by the parser.
     */
    explicit FParser(FLexer& lexer);

    /**
     * @brief Parses the token stream and returns a list of statements.
     * @return A list of parsed statements.
     */
    StatementList Parse();
};
