/**
 * @file statement_parser.hpp
 * @brief Declaration of the FStatementParser class.
 */

// Ensure this file is included only once
#pragma once

 // Include the interface for language statements
#include "statement/interface/statement.hpp"

// Include the interface for expressions
#include "expression/interface/expression.hpp"

// Include the expression parser header file
#include "expression_parser.hpp"

// Forward declaration of FLexer class
class FLexer;

/**
 * @brief Parser class for language statements.
 *
 * This class is responsible for parsing tokens generated by the lexer
 * into statement objects representing different language constructs.
 */
class FStatementParser
{
    // Reference to the lexer used by the parser
    FLexer& m_lexer;

    // Reference to the expression parser
    FExpressionParser& m_expressionParser;

public:

    /**
     * @brief Constructs a statement parser with the given lexer and expression parser.
     *
     * @param lexer The lexer to be used by the parser.
     * @param expressionParser The expression parser to be used by the parser.
     */
    explicit FStatementParser(FLexer& lexer, FExpressionParser& expressionParser);
    
    /**
     * @brief Parses the next statement from the token stream and returns a statement object.
     *
     * @return StatementPtr A pointer to the parsed statement object.
     */
    StatementPtr ParseStatement();

private:

    /**
     * @brief Parses an assignment statement from the token stream.
     *
     * @return StatementPtr A pointer to the parsed assignment statement.
     */
    StatementPtr ParseAssignmentStatement();

    /**
     * @brief Parses a variable declaration statement from the token stream.
     *
     * @return StatementPtr A pointer to the parsed variable declaration statement.
     */
    StatementPtr ParseVarDeclarationStatement();

    /**
     * @brief Parses a print statement from the token stream.
     *
     * @return StatementPtr A pointer to the parsed print statement.
     */
    StatementPtr ParsePrintStatement();
};

// Define a pointer type for FStatementParser using unique_ptr
using StatementParserPtr = std::unique_ptr<FStatementParser>;
